In [1]:
from google.colab import files
uploaded = files.upload()

Saving loanapproval.csv to loanapproval.csv

# Import libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [3]:
df = pd.read_csv("loanapproval.csv")

In [4]:
df.head()

,applicant_id,age,gender,marital_status,annual_income,loan_amount,credit_score,num_dependents,existing_loans_count,employment_status,loan_approved
0,1,59,Male,Divorced,100073,7169,793,1,1,Unemployed,1
1,2,49,Male,Married,112197,23556,789,0,2,Employed,1
2,3,35,Male,Divorced,84429,27052,372,1,4,Unemployed,0
3,4,63,Female,Single,124195,11313,808,3,4,Self-employed,1
4,5,28,Female,Married,81627,13315,689,0,1,Unemployed,1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   applicant_id          1000 non-null   int64
 1   age                   1000 non-null   int64
 2   gender                1000 non-null   object
 3   marital_status        1000 non-null   object
 4   annual_income         1000 non-null   int64
 5   loan_amount           1000 non-null   int64
 6   credit_score          1000 non-null   int64
 7   num_dependents        1000 non-null   int64
 8   existing_loans_count  1000 non-null   int64
 9   employment_status     1000 non-null   object
 10  loan_approved         1000 non-null   int64
dtypes: int64(8), object(3)
memory usage: 86.1+ KB

#data preprocessing

In [6]:
df.isnull().sum()

applicant_id            0
age                     0
gender                  0
marital_status          0
annual_income           0
loan_amount             0
credit_score            0
num_dependents          0
existing_loans_count    0
employment_status       0
loan_approved           0
dtype: int64

In [7]:
df.drop_duplicates(inplace=True)

In [8]:
X = df.drop("loan_approved", axis=1)
Y = df["loan_approved"]

In [9]:
X

,applicant_id,age,gender,marital_status,annual_income,loan_amount,credit_score,num_dependents,existing_loans_count,employment_status
0,1,59,Male,Divorced,100073,7169,793,1,1,Unemployed
1,2,49,Male,Married,112197,23556,789,0,2,Employed
2,3,35,Male,Divorced,84429,27052,372,1,4,Unemployed
3,4,63,Female,Single,124195,11313,808,3,4,Self-employed
4,5,28,Female,Married,81627,13315,689,0,1,Unemployed
...,...,...,...,...,...,...,...,...,...,...
995,996,53,Female,Married,135598,6014,767,3,2,Employed
996,997,22,Male,Single,139028,15103,662,0,0,Self-employed
997,998,34,Female,Married,147517,21986,582,0,2,Employed
998,999,60,Female,Divorced,73161,49781,635,4,0,Unemployed
999,1000,60,Female,Single,141316,35471,461,1,1,Unemployed

In [10]:
Y

0      1
1      1
2      0
3      1
4      1
      ..
995    1
996    1
997    1
998    1
999    1
Name: loan_approved, Length: 1000, dtype: int64

#one hot encoding

In [11]:
X = pd.get_dummies(X, columns=['gender', 'marital_status', 'employment_status'], drop_first=True)

#Split dataset

In [12]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

#Feature scaling

In [13]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

#Train model

In [14]:
model = LogisticRegression()
model.fit(X_train, Y_train)

LogisticRegression()

In [15]:
y_pred = model.predict(X_test)

#Evaluate model

In [16]:
accuracy = accuracy_score(Y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.865

In [17]:
cm = confusion_matrix(Y_test, y_pred)
print(cm)

[[ 39  16]
 [ 11 134]]

In [18]:
cr = classification_report(Y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.78      0.71      0.74        55
           1       0.89      0.92      0.91       145

    accuracy                           0.86       200
   macro avg       0.84      0.82      0.83       200
weighted avg       0.86      0.86      0.86       200

#ROC-AUC Score

In [19]:
from sklearn.metrics import roc_auc_score
roc = roc_auc_score(Y_test, y_pred)
print("ROC-AUC:", roc)

ROC-AUC: 0.816614420062696

#Train Decision Tree

In [20]:
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier(criterion='gini', random_state=42)
dt_model.fit(X_train, Y_train)

DecisionTreeClassifier(random_state=42)

In [21]:
dt_model_pred = dt_model.predict(X_test)

In [22]:
print("Accuracy:", accuracy_score(Y_test, dt_model_pred))
print(confusion_matrix(Y_test, dt_model_pred))
print(classification_report(Y_test, dt_model_pred))

Accuracy: 0.98
[[ 51   4]
 [  0 145]]
              precision    recall  f1-score   support

           0       1.00      0.93      0.96        55
           1       0.97      1.00      0.99       145

    accuracy                           0.98       200
   macro avg       0.99      0.96      0.97       200
weighted avg       0.98      0.98      0.98       200

In [23]:
print("ROC-AUC:", roc_auc_score(Y_test, dt_model_pred))

ROC-AUC: 0.9636363636363636

#Train Random Forest

In [24]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [25]:
rf_model_pred = rf_model.predict(X_test)

In [26]:
print("Accuracy:", accuracy_score(Y_test, rf_model_pred))
print(confusion_matrix(Y_test, rf_model_pred))
print(classification_report(Y_test, rf_model_pred))

Accuracy: 0.97
[[ 49   6]
 [  0 145]]
              precision    recall  f1-score   support

           0       1.00      0.89      0.94        55
           1       0.96      1.00      0.98       145

    accuracy                           0.97       200
   macro avg       0.98      0.95      0.96       200
weighted avg       0.97      0.97      0.97       200

In [27]:
print("ROC-AUC:", roc_auc_score(Y_test, rf_model_pred))

ROC-AUC: 0.9454545454545454

#Feature importance

In [28]:
importance = pd.DataFrame({'feature': X.columns, 'importance': rf_model.feature_importances_})
importance = importance.sort_values('importance', ascending=False)
print(importance)

                            feature  importance
5                    num_dependents    0.207425
4                      credit_score    0.201879
6              existing_loans_count    0.163446
11     employment_status_Unemployed    0.122165
2                     annual_income    0.114605
0                      applicant_id    0.050938
3                       loan_amount    0.049938
1                               age    0.046558
10  employment_status_Self-employed    0.018061
9             marital_status_Single    0.009482
7                       gender_Male    0.008478
8            marital_status_Married    0.007026

#Save the model

In [29]:
import joblib
joblib.dump(model, "credit_model.pkl")
joblib.dump(dt_model, "dt_model.pkl")
joblib.dump(rf_model, "rf_model.pkl")
joblib.dump(X.columns.tolist(), "feature_names.pkl")

from sklearn.metrics import classification_report
metrics = {
    "Accuracy": accuracy_score(Y_test, rf_model_pred),
    "ROC-AUC": roc_auc_score(Y_test, rf_model_pred),
    "Classification_Report": classification_report(Y_test, rf_model_pred),
    "Confusion_Matrix": confusion_matrix(Y_test, rf_model_pred)
}

joblib.dump(metrics, "metrics.pkl")

['metrics.pkl']

In [30]:
model = joblib.load("credit_model.pkl")